// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp7R27qlwvpr5v41_L4YO9OtT8stdR0gs',
    appId: '1:457501069566:web:c6ce360682d59a3ad995af',
    messagingSenderId: '457501069566',
    projectId: 'swift-shop-4e300',
    authDomain: 'swift-shop-4e300.firebaseapp.com',
    databaseURL: 'https://swift-shop-4e300-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swift-shop-4e300.appspot.com',
    measurementId: 'G-RB68QCJ4ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF1QAFmqiqehPx6xZTrMY8j_3huuuAHWo',
    appId: '1:457501069566:android:6506e0e4bb95d002d995af',
    messagingSenderId: '457501069566',
    projectId: 'swift-shop-4e300',
    databaseURL: 'https://swift-shop-4e300-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swift-shop-4e300.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLMavicY8EuTBE0cqNbm6_k-bmMBTdpaA',
    appId: '1:457501069566:ios:6d49302471c9691ad995af',
    messagingSenderId: '457501069566',
    projectId: 'swift-shop-4e300',
    databaseURL: 'https://swift-shop-4e300-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swift-shop-4e300.appspot.com',
    iosBundleId: 'com.example.mapProject',
  );
}
